run:
  output_dir: results
  parallelism: 8
  resume: false
  timeout_seconds: 60
  datasets:
  - id: netlib
    name: netlib
    dataset_options:
      subset: feasible
  - id: maros_meszaros
    name: maros_meszaros

solvers:
- id: rescale_25
  solver: scs
  settings: {eps_abs: 1.0e-06, eps_rel: 1.0e-06, max_iters: 1000000, adaptive_diag_scale: 10, den_floor_frac: 1.0e-03, acceleration_interval: 5, num_l2_passes: -1, rescaling_min_iters: 25}
- id: rescale_50
  solver: scs
  settings: {eps_abs: 1.0e-06, eps_rel: 1.0e-06, max_iters: 1000000, adaptive_diag_scale: 10, den_floor_frac: 1.0e-03, acceleration_interval: 5, num_l2_passes: -1, rescaling_min_iters: 50}
- id: rescale_100
  solver: scs
  settings: {eps_abs: 1.0e-06, eps_rel: 1.0e-06, max_iters: 1000000, adaptive_diag_scale: 10, den_floor_frac: 1.0e-03, acceleration_interval: 5, num_l2_passes: -1, rescaling_min_iters: 100}
- id: rescale_200
  solver: scs
  settings: {eps_abs: 1.0e-06, eps_rel: 1.0e-06, max_iters: 1000000, adaptive_diag_scale: 10, den_floor_frac: 1.0e-03, acceleration_interval: 5, num_l2_passes: -1, rescaling_min_iters: 200}
- id: damp_0.1
  solver: scs
  settings: {eps_abs: 1.0e-06, eps_rel: 1.0e-06, max_iters: 1000000, adaptive_diag_scale: 10, den_floor_frac: 1.0e-03, acceleration_interval: 5, num_l2_passes: -1, diag_scale_damp: 0.1}
- id: damp_0.5
  solver: scs
  settings: {eps_abs: 1.0e-06, eps_rel: 1.0e-06, max_iters: 1000000, adaptive_diag_scale: 10, den_floor_frac: 1.0e-03, acceleration_interval: 5, num_l2_passes: -1, diag_scale_damp: 0.5}
