run:
  output_dir: results
  parallelism: 8
  resume: true
  timeout_seconds: 100
  datasets:
  - id: netlib
    name: netlib
    dataset_options:
      subset: feasible
  - id: maros_meszaros
    name: maros_meszaros
  - id: miplib
    name: miplib
    dataset_options:
      max_size_mb: 5.0

solvers:
- id: ctrl_ads3
  solver: scs
  settings:
    eps_abs: 1.0e-06
    eps_rel: 1.0e-06
    max_iters: 1000000
    adaptive_diag_scale: 3
    acceleration_interval: 5
    num_l2_passes: -1

- id: joint_spec
  solver: scs
  settings:
    eps_abs: 1.0e-06
    eps_rel: 1.0e-06
    max_iters: 1000000
    adaptive_diag_scale: 4
    scale: 0.1
    diag_scale_damp: 0.25
    acceleration_interval: 5
    num_l2_passes: -1

- id: joint_spec_d5
  solver: scs
  settings:
    eps_abs: 1.0e-06
    eps_rel: 1.0e-06
    max_iters: 1000000
    adaptive_diag_scale: 4
    scale: 0.1
    diag_scale_damp: 0.5
    acceleration_interval: 5
    num_l2_passes: -1
