run:
  output_dir: results
  parallelism: 6
  resume: true
  timeout_seconds: 60
  datasets:
    - id: sdplib_small
      name: sdplib
      dataset_options:
        max_size_mb: 1.0
    - name: liu_pataki

solvers:
  - id: scs_default_new
    solver: scs
    settings:
      eps_abs: 1.0e-6
      eps_rel: 1.0e-6
      max_iters: 1000000

  - id: scs_diag3_aa
    solver: scs
    settings:
      eps_abs: 1.0e-6
      eps_rel: 1.0e-6
      max_iters: 1000000
      adaptive_diag_scale: 3
